use sendok_laravel;
--
-- AUTO_INCREMENT de la tabla `failed_jobs`
--
ALTER TABLE `failed_jobs`
   MODIFY `id`  INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

--
-- AUTO_INCREMENT de la tabla `migrations`
--
ALTER TABLE `migrations`
   MODIFY `id`  INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

--
-- AUTO_INCREMENT de la tabla `users`
--
  ALTER TABLE `users`
  MODIFY `id`  INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
COMMIT;
